name: Build (Linux)

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        mode:
          - debug
          - release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/.xmake
          key: xmake-linux-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-linux-

      - run: |
          sudo apt install -y build-essential

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p linux -v -y

      - run: |
          xmake -v -y

      - uses: actions/upload-artifact@v4
        with:
          name: rkcfgtool-${{ matrix.mode }}-linux-x64-${{ github.sha }}
          path: |
            build/linux/x64/${{ matrix.mode }}
