name: Build (Windows)

on:
  push:
    branches: [ "*" ]

jobs:
  build:
    strategy:
      matrix:
        mode:
          - debug
          - release
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: xmake-io/github-action-setup-xmake@v1

      - uses: actions/cache@v4
        with:
          path: |
            ~/AppData/Local/.xmake
          key: xmake-windows-${{ hashFiles('xmake.lua') }}
          restore-keys: |
            xmake-windows-

      - uses: microsoft/setup-msbuild@v2

      - run: |
          xmake repo -u

      - run: |
          xmake f -a x64 -m ${{ matrix.mode }} -p windows -v -y

      - run: |
          xmake -v -y
      
      - run: |
          Copy-Item "$env:USERPROFILE\AppData\Local\.xmake\packages\i\icu4c\*\*\bin\*.dll" -Destination build\windows\x64\${{ matrix.mode }} -Force

      - uses: actions/upload-artifact@v4
        with:
          name: rkcfgtool-${{ matrix.mode }}-windows-x64-${{ github.sha }}
          path: |
            build/windows/x64/${{ matrix.mode }}
